version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'

  mongo:
    image: mongo:4.2.5

  server:
    build: .
    environment:
      WAIT_HOST: mongo:27017
    volumes:
      - ./static:/app/static
    ports:
      - '8080:8080'

